/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TransactionsIndexImport } from './routes/transactions/index'
import { Route as TransactionsAddImport } from './routes/transactions/add'
import { Route as TransactionsEditIdImport } from './routes/transactions/edit.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsIndexRoute = TransactionsIndexImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsAddRoute = TransactionsAddImport.update({
  id: '/transactions/add',
  path: '/transactions/add',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsEditIdRoute = TransactionsEditIdImport.update({
  id: '/transactions/edit/$id',
  path: '/transactions/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions/add': {
      id: '/transactions/add'
      path: '/transactions/add'
      fullPath: '/transactions/add'
      preLoaderRoute: typeof TransactionsAddImport
      parentRoute: typeof rootRoute
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions/edit/$id': {
      id: '/transactions/edit/$id'
      path: '/transactions/edit/$id'
      fullPath: '/transactions/edit/$id'
      preLoaderRoute: typeof TransactionsEditIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/transactions/add': typeof TransactionsAddRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transactions/add': typeof TransactionsAddRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/transactions/add': typeof TransactionsAddRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/transactions/add'
    | '/transactions'
    | '/transactions/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/transactions/add' | '/transactions' | '/transactions/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/transactions/add'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TransactionsAddRoute: typeof TransactionsAddRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  TransactionsEditIdRoute: typeof TransactionsEditIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TransactionsAddRoute: TransactionsAddRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  TransactionsEditIdRoute: TransactionsEditIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/transactions/add",
        "/transactions/",
        "/transactions/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/transactions/add": {
      "filePath": "transactions/add.tsx"
    },
    "/transactions/": {
      "filePath": "transactions/index.tsx"
    },
    "/transactions/edit/$id": {
      "filePath": "transactions/edit.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
